### ISSUE TITLE
Add ckeditor configuration to theme

### ISSUE THREAD

**Issue by timdavison** [misd-service-development/drupal-cambridge-theme#119]
Some of the sites that were created from the f2 starter have a CKeditor configuration in a local copy of the theme (in expectation that it would in time become part of the theme). That time has come.

Add a ckeditor.styles.js file to the root theme directory. Suggested content as follows (although open to change!).

Note this will remove some inline styles from the current setup and add the ability to float images left and right.

=========
/*
Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
For licensing, see LICENSE.html or http://ckeditor.com/license
*/

/*
 * This file is used/requested by the 'Styles' button.
 * The 'Styles' button is not enabled by default in DrupalFull and DrupalFiltered toolbars.
 */
if(typeof(CKEDITOR) !== 'undefined') {
    CKEDITOR.addStylesSet( 'drupal',
    [
            /* Inline Styles */

            // These are core styles available as toolbar buttons. You may opt enabling
            // some of them in the "Styles" drop-down list, removing them from the toolbar.
            { name : 'Strikethrough'  , element : 'strike' },
            { name : 'Subscript'    , element : 'sub' },
            { name : 'Superscript'    , element : 'sup' },
            { name : 'Marker: Yellow' , element : 'span', styles : { 'background-color' : 'Yellow' } },
            { name : 'Computer Code'  , element : 'code' },

            /* Object Styles */
            {
                    name : 'Image on Left',
                    element : 'img',
                    attributes :
                    {
                            'style' : 'padding: 0; margin: 5px 10px 5px 0',
                            'border' : '1',
                            'align' : 'left'
                    }
            },

            {
                    name : 'Image on Right',
                    element : 'img',
                    attributes :
                    {
                            'style' : 'padding: 0; margin: 5px 0 5px 10px',
                            'border' : '2',
                            'align' : 'right'
                    }
            }
    ]);
}

**Comment by JeebsUK** [comment]
Looks OK to me - pending input from Andy and/or Magda.
