### ISSUE TITLE
Links are sometimes coloured black and so can't be distinguished from other text.

### ISSUE THREAD

**Issue by timdavison** [misd-service-development/drupal-cambridge-theme#122]
This could be fixed by the following:
.campl-message-box a, table a {
  color: #0065b8;
}

NB. this will also turn :visited links blue - maybe they should be purple?
.campl-message-box a:visited, table a:visited {
  color: #551A8B;
}

**Comment by JeebsUK** [comment]
I would make visited links purple - it's known standard web behaviour - so so long as that colour is accessibility compliant that seems a good solution to me.

**Comment by timdavison** [comment]
Ok - I'll do that
