### ISSUE TITLE
page loads become unacceptably slow with large menu

### ISSUE THREAD

**Issue by jhnc** [misd-service-development/drupal-cambridge-theme#40]
The drupal theme wants the horizontal menu to have "expanded" set in the menu_block. However, the menu_block code calls menu_tree_all_data() in this case.

As number of menu items increases, page loads become progressively slower. With ~3000 items, I see >30s. I expect to want to have 30,000+ items eventually. As it stands, response is probably unacceptably slow beyond a couple of hundred menu items.

The horizontal menu does not allow (in the desktop view) for expanding more than one level, so simply replacing the horizontal menu with a barebones version seems the obvious workaround. Unfortunately, it looks as though the javascript that implements the mobile navigation wants (at least) the (arbitrary depth) active trail.

I already have a hook_menu_block_tree_alter() to prune the menus into such a barebones version so that unnecessary data isn't sent over the web with every page. However, this hook is not called early enough to bypass the menu_tree_all_data() call.

It would be great if the navigation could be made to scale.

**Comment by thewilkybarkid** [comment]
Fixed by #81.
