### ISSUE TITLE
full pager ajax doesn't work

### ISSUE THREAD

**Issue by alt36** [misd-service-development/drupal-cambridge-theme#78]
With a paginated view with a full pager, even if I set "use ajax: yes", the pager links aren't loaded via ajax. The ajax loading is kind of essential for uses like the "Publications" section at:

http://www.ch.cam.ac.uk/person/df246

Without ajax, going forward/backwards takes the user back to the top of the page rather than the top of the publications section

**Comment by thewilkybarkid** [comment]
Looks the the JavaScript is assuming that the `ul` has the `pager` class. From memory this was stripped as it brought in a load of Drupal styles that conflict, shouldn't be too difficult to overwrite them.
