### ISSUE TITLE
Main menu item must currently by called "Home"

### ISSUE THREAD

**Issue by alt36** [misd-service-development/drupal-cambridge-theme#82]
template.php has the magic string "Home" hard-coded in a number of places - lots of

if ($element['#title'] != t('Home')) { 
...
} 

and so on. This means that if "Home" is not present in the nav menu (suppose you instead have "Site Home" which links to <front>), then in the left nav bar you get both an item with a title of $site_name, *and* another item entitled "Site Home", both of which link to <front>.

Rather than having the hard-coded magic string "Home", would it make sense to either a) have this be configurable, or perhaps even better b) have the relevant logic in template.php look for something that links to <front> rather than assuming it's called "Home"?

**Comment by thewilkybarkid** [comment]
Option b should work (and would be a lot better!).
